// autogenerated program class is not auto-sealed :pain:
#pragma warning disable CA1852

using System.Diagnostics;
using System.Net.Http.Headers;
using CliFx;
using Microsoft.Extensions.DependencyInjection;
using Tgstation.Server.Client;
using Tgstation.Server.CommandLineInterface.Middlewares;
using Tgstation.Server.CommandLineInterface.Models;
using Tgstation.Server.CommandLineInterface.Services;

var sw = Stopwatch.StartNew();

var app = new CliApplicationBuilder()
    .AddCommandsFromThisAssembly()
    .UseTypeActivator(ConfigureServices)
    .SetExecutableName(ApplicationInfo.ApplicationName.ToLowerInvariant())
    .SetDescription("Command line interface for tgstation-server")
    .Build();

sw.Stop();

Console.WriteLine($"Startup took {sw.ElapsedMilliseconds}ms");

return await app.RunAsync();

static IServiceProvider ConfigureServices(IEnumerable<Type> commands)
{
    var services = new ServiceCollection();

    // Register services here

    services.AddSingleton<IApplicationInfo, ApplicationInfo>();

    services.AddSingleton<IServerClientFactory, ServerClientFactory>(serviceProvider =>
    {
        var appInfo = serviceProvider.GetRequiredService<IApplicationInfo>();
        return new ServerClientFactory(new ProductHeaderValue(appInfo.Name, appInfo.Version.ToString()));
    });

    services.AddSingleton<IPersistenceManager, PersistenceManager>();
    services.AddSingleton<IRemoteRegistry, RemoteRegistry>();
    services.AddSingleton<ISessionManager, SessionManager>();
    services.AddSingleton<ITgsClientManager, TgsClientManager>();
    services.AddSingleton<IMiddlewarePipeline, MiddlewarePipeline>();

    // Register converters here

    services.AddSingleton<InstanceSelectorConverter>();

    // Handle commands

    foreach (var command in commands)
    {
        services.UseCommand(command);
    }

    return services.BuildServiceProvider();
}
